alias gitreport='~/bin/gitreport.sh'
alias gitpullall='~/bin/gitpullall.sh'
aliat clonemt='~/bin/clonemt'
aliat clonefit='~/bin/clonefit'

alias xclip='xclip -selection c'
alias find='find "$@" 2>/dev/null'
alias ls='ls -F'
alias la='ls -Fla'
alias LS='sudo ls -F'
alias LA='sudo la -Fla'
